支持设置base url
wechatpay-apiv3/wechatpay-java pull request #16
Opened 2022-07-25 02:52 UTC by lianup

2022-07-25 03:59 UTC, xy-peng reviewed
你的想法提醒了我，我们应该重新评估各种参数。

+ Config是密码相关的配置，或者说商户的配置
+ HttpClient是网络请求的参数
+ XXXService需要的是系统运行的参数

这样看，把 baseUrl 放到 service 更合适？

2022-07-25 03:59 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +  public AppService(HttpClient httpClient, String baseUrl) {
未来参数可能越来越多，为了兼容，构造函数会越来越多越来越复杂，是否考虑提供 builder 来构造？

2022-07-25 03:59 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/Config.java
> +  String getBaseUrl();
提供一个默认的方法？

2022-07-25 06:21 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +  public AppService(HttpClient httpClient, String baseUrl) {
是的，提供builder比较合适，因为还可能需要设置敏感信息加解密器等。

2022-07-25 06:25 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/Config.java
> +  String getBaseUrl();
根据上面的建议，如果放在 Service 的 Builder 中设置，这个方法可以去掉了

2022-07-25 09:13 UTC, TheNorthMemory commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
不带路径的baseUrl没有太大问题，拔特，如果带了路径，则效果会有部分偏差，详情可参阅 [RFC 3986, section 5.2](https://tools.ietf.org/html/rfc3986#section-5.2) ，或者 [GuzzleHttp QuickStart](https://docs.guzzlephp.org/en/stable/quickstart.html)，建议base_url值末尾，带上 slash。

2022-07-25 09:15 UTC, xy-peng requested changes

2022-07-25 09:15 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +    this.httpClient = httpClient;
不检查为空吗？

2022-07-25 09:40 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
是这样的，因为服务的协议文件里面定义url为`https://api.mch.weixin.qq.com`，接口的具体路径后缀为 `/v3/xxxxx`，所以我就这样定义了

2022-07-25 10:12 UTC, TheNorthMemory commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
> 是这样的，因为服务的协议文件里面定义url为`https://api.mch.weixin.qq.com`，接口的具体路径后缀为 `/v3/xxxxx`，所以我就这样定义了

建议洁癖一下，用成熟`lib`功能代替字符串链接，例如[HttpUrl](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/):

```java
HttpUrl url = HttpUrl.parse("http://who-let-the-dogs.out").newBuilder()\ 
.addPathSegment("Who?")\ 
.query("Who?")\ .fragment("Who?")\ 
.build();\ 
System.out.println(url);
```

自动解决`percent encoding`事项，潜在的 `IDNA` 也解决了。

2022-07-26 02:11 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
嗯，不过协议契约里面只能拿到baseUrl和具体路径后缀，你举的例子是跟okhttp实现相关的，如果要用实现无关的，之前在考虑过这种方式：
1. 先用baseUrl+具体后缀构造一个URL类（因为协议里只能获得baseUrl+具体后缀，要获得上述参数需要自行解析）
2. 再从URL中获得上述参数设置一个URI类

这样会略嫌麻烦，但能正确编码。

2022-07-26 03:56 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
我觉得用 OkHttp 的库是无妨的。无论如何，wechatpay-java 本身就依赖了 OkHttp，用 OkHttp.HttpUrl 也不影响具体 httpclient 的实现。

2022-07-26 06:19 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/http/Constant.java
> +  public static final String DEFAULT_BASE_URL = "https://api.mch.weixin.qq.com";
可以用OkHttp.HttpUrl的方式，和上述的1、2步骤类似，要省略1步骤，可能需要自己解析url来获取值。

2022-07-26 08:55 UTC, xy-peng requested changes
@lianup 文档还需要改

2022-07-26 09:09 UTC, TheNorthMemory approved these changes
辛苦了，可以支持apihk了

2022-07-26 11:49 UTC, xy-peng approved these changes

2022-07-26 11:50 UTC, merged