增加build.yml
wechatpay-apiv3/wechatpay-java pull request #2
Opened 2022-07-08 10:40 UTC by lianup

2022-07-08 12:16 UTC, xy-peng requested changes

2022-07-08 12:16 UTC, xy-peng commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
全平台，请补充上

+ macos amd64/arm64
+ windows

2022-07-08 12:16 UTC, xy-peng commented on .github/workflows/build.yml
> +      - uses: actions/checkout@v2
我看到 checkout 已经发布了 v3，是否采用最新的版本？

2022-07-08 12:16 UTC, xy-peng commented on .github/workflows/build.yml
> +        uses: actions/setup-java@v2
setup-java 也到了v3

2022-07-08 12:16 UTC, xy-peng commented on .github/workflows/build.yml
> +        uses: actions/setup-java@v2
```groovy
- uses: actions/setup-java@v3
  with:
    distribution: 'adopt'
    java-version: ${{ matrix.java-version }}
    cache: 'gradle'
```

打开 cache ？

2022-07-08 15:16 UTC, xy-peng commented on .github/workflows/build.yml
> +        run: ./gradlew build
还需要一个 test 的 job

2022-07-11 02:31 UTC, lianup commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
根据 https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on，
windows、macos、ubuntu 都有多种不同版本，需要都补充上吗？还是覆盖 xx-latest 即可？

2022-07-11 03:42 UTC, lianup commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
我补充了三种平台的最新版本

2022-07-11 06:19 UTC, xy-peng approved these changes

2022-07-11 09:35 UTC, xy-peng reviewed
spotlessCheck 要在 build 中加入吗

2022-07-13 02:21 UTC, merged