增加敏感信息加解密器
wechatpay-apiv3/wechatpay-java pull request #40
Opened 2022-09-19 11:19 UTC by lianup

# 变更
1. 增加 PrivacyCipher，提供敏感信息加密，解密方法
2. 增加对应的工具类和Test方法

# 使用
假设TestService具有test接口，TestRequest具有需要加密的敏感信息a，TestResponse具有需要解密的敏感信息b。
1. TestService构造函数支持传入PrivacyCipher 
```java
TestService(HttpClient client, PrivacyCipher cipher)
```
3. test接口加密敏感信息：
```java
// testRequest为原请求参数，encryptRequest为testRequest的拷贝对象
TestRequest encrytRequest = ObjectUtils.deepCopy(testRequest, encryptRequest);
// 加密请求中的敏感信息，后续使用encryptRequest发送请求
encrypt(testRequest, encryptRequest, encryptor);
```
4. test接口解密敏感信息：
```java
// testResponse为原返回参数，encryptResponse为testResponse的拷贝对象
TestResponse decryptResponse = ObjectUtils.deepCopy(testResponse, decryptResponse);
// 解密返回中的敏感信息，后续使用decryptResponse作为方法返回
decrypt(testResponse decryptResponse,decryptor);
```

2022-09-19 12:07 UTC, EmmetZC requested changes

2022-09-19 12:07 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/util/ObjectUtil.java
> +  public static <T> T deepCopy(Object object, Class<T> tClass) {
这么定义的话，可以这样调用吧，这是想要的行为吗？
```
Object1 object1 = new Object1();
Object2 copyWithWrongType = ObjectUtil.deepCopy(object1, Object2.class);
```

能不能这样？
```suggestion
  public static <T> T deepCopy(T object) {
    Class<?> tClass = object.getClass();
```

2022-09-19 12:07 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/cipher/PrivacyCipher.java
> +    for (Field field : obj.getClass().getDeclaredFields()) {
把原对象`obj`传进来的目的是啥？能不能只读写`decryptObj`？

2022-09-20 02:05 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/util/ObjectUtil.java
> +  public static <T> T deepCopy(Object object, Class<T> tClass) {
似乎不行，因为运行时T类型会被擦除，所以无法通过`getClass`获得运行时类。所以需要提供实际的tClass

2022-09-20 06:09 UTC, closed without merging