重新生成业务代码
wechatpay-apiv3/wechatpay-java pull request #41
Opened 2022-09-23 09:26 UTC by lianup

refactor:修改Model的toString方式
fix:修正多个queryParam拼接方式
feat:新增敏感信息加解密注解

2022-09-25 14:26 UTC, xy-peng requested changes

2022-09-25 14:26 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +                new JsonRequestBody.Builder().body(GsonUtil.getGson().toJson(realRequest)).build())
`new JsonRequestBody.Builder().body(GsonUtil.getGson().toJson(realRequest)).build())`

这段代码需要思考一下才明白它的作用，建议封装。

2022-09-26 02:44 UTC, lianup commented on core/src/test/java/com/wechat/pay/java/core/util/StringUtilTest.java
> +    assertNotNull(toIndentedString(request));
已改为明确的test case

2022-09-26 07:44 UTC, xy-peng approved these changes

2022-09-26 08:39 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/util/StringUtil.java
> +    return o.toString().replace("\n", "\n    ");
这个写法有点怪，第一行不会缩进，最后一行可能会有额外缩进（如果有尾部`\n`）。可能功能是你想要的，但是看上去和这个名字不怎么匹配。

2022-09-26 08:46 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/util/StringUtil.java
> +    return o.toString().replace("\n", "\n    ");
是的，可以在注释上加上第一行不会缩进。
这里是参考openapi-generator的.mustache写的：
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/pojo.mustache

2022-09-26 08:50 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/util/StringUtil.java
> +    return o.toString().replace("\n", "\n    ");
嗯嗯，说明一下好了。

2022-09-26 08:51 UTC, EmmetZC approved these changes

2022-09-26 08:54 UTC, merged