根据优化建议修改
wechatpay-apiv3/wechatpay-java pull request #6
Opened 2022-07-15 07:13 UTC by lianup

2022-07-16 10:44 UTC, xy-peng requested changes
我不建议在方法声明加上对应的 exception：

1. 所有的接口上都加上，跟没加一样
2. RuntimeExcpetion 是不用加的
3. 本来我们是希望开发者按需处理的
4. 函数文档中有列出 throw 的

我们通过提供文档更“明显”让开发者知道会抛出异常，说明为什么我们使用 unchecked exception，结合常见的框架把最佳实践教给开发者的方式，让开发者做好错误处理？

@EmmetZC @Eric-Lee-Handyman 一起讨论下。

如果一定要列，我觉得根据继承关系，只列一个 `WechatPayException` ?

2022-07-16 10:44 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +      // 添加 query param
path 参数没有转义？

2022-07-16 10:44 UTC, xy-peng commented on core/src/test/java/com/wechat/pay/java/core/http/OkHttpClientAdapterTest.java
> +  public void testExecuteSendPostReqWithJsonBody() {
如果要简化， `Send` 也可以干掉，毕竟 `execute` 和 `send` 两个动词了

2022-07-18 08:10 UTC, lianup commented on core/src/test/java/com/wechat/pay/java/core/http/OkHttpClientAdapterTest.java
> +  public void testExecuteSendPostReqWithJsonBody() {
之前的名称超过32个字符了，所以改短一点。这些可以方法名在重新设计测试方法时一并改了。

2022-07-18 14:39 UTC, xy-peng requested changes

2022-07-18 14:39 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +        throw new IllegalArgumentException(
1. 使用 `isEmpty()` 比 `size() == 0` 要好。举个例子，`LinkedList.size()` 的时间复杂度是 o(n)，而 `isEmpty()` 是 o(1)。
2. `requireNonNull()` 还是可以用呀，补充一个是否为空的判断就可以了。

2022-07-18 14:39 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +  private String encodeParam(String param) {
1. 为什么不在 http 下提供一个 UrlEncoder 的类呢
2. 命名我倾向于使用 urlEncode()，encodeParam 并没有说明使用的何种编码，在代码上下文中更易读

2022-07-18 14:39 UTC, xy-peng commented on .gitignore
> +buildSrc/.gradle/*
把 `.gradle/*` 改成 `.gradle/` 就行了

2022-07-19 03:01 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payment/app/AppService.java
> +  private String encodeParam(String param) {
1. 我把这个方法封装起来只是为了统一处理错误，使用的这个类本身叫做URLEncode，再单独封装一个差不多命名的类，只提供这样一个方法，感觉有点没必要，所以就放在这里了。

2022-07-19 07:29 UTC, xy-peng approved these changes

2022-07-19 07:31 UTC, merged