增加下单并生成调起支付数据拓展类
wechatpay-apiv3/wechatpay-java pull request #64
Opened 2022-11-17 06:53 UTC by lianup

如题。

2022-11-18 16:44 UTC, xy-peng requested changes
1. readme增加介绍，不然大家找不到
2. 直接传一个 Signer ？或者在 Config 中增加 createSigner()，直接用 config 初始化多简单。进一步让 ServiceExtension 集成至 Service，这样开发者可以直接用 ServiceExtension，而不用同时构造 Service 和 ServiceExtension 了

2022-11-18 16:44 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/partnerpayments/app/AppServiceExtension.java
> +      this.privateKey = PemUtil.loadPrivateKeyFromString(privateKeyStr);
这里也跟RSA产生了耦合。

2022-11-18 16:44 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/partnerpayments/jsapi/model/PrepayWithRequestPaymentResponse.java
> +  @SerializedName("timeStamp")
app/jsapi的timestamp不一致，在sdk里要不要修复一把？

2022-11-18 16:44 UTC, xy-peng commented on service/src/main/java/com/wechat/pay/java/service/partnerpayments/jsapi/JsapiServiceExtension.java
> +    public Builder merchantSerial(String merchantSerial) {
商户API证书序列号，用不到，用一个全0的字符串占位即可？

虽然可能是坑，但如果是自己构造一个Signer内部用，其实并无关系。

2022-11-21 03:01 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/partnerpayments/jsapi/JsapiServiceExtension.java
> +    Signer signer = new RSASigner(merchantSerial, privateKey);
多提供一个signType接口，默认为RSA，其他的用户可以自行传，这样如何？

2022-11-22 03:36 UTC, lianup commented
> 1. readme增加介绍，不然大家找不到
> 2. 直接传一个 Signer ？或者在 Config 中增加 createSigner()，直接用 config 初始化多简单。进一步让 ServiceExtension 集成至 Service，这样开发者可以直接用 ServiceExtension，而不用同时构造 Service 和 ServiceExtension 了

已在Config中增加`createSigner`，通过直接传入Config来使用ServiceExtension。

2022-11-28 08:49 UTC, EmmetZC commented on service/src/example/java/com/wechat/pay/java/service/partnerpayments/jsapi/JsapiServiceExtensionExample.java
> +  public static com.wechat.pay.java.service.partnerpayments.jsapi.model
为啥这里要写把 `namespace` 都要写出来？

2022-11-28 15:22 UTC, xy-peng approved these changes

2022-11-28 15:45 UTC, EmmetZC commented on README.md
> +    // 调用service.setXxx(val)设置所需参数，具体参数可见Request定义
这里好像还得是 `request.setXxx`？为啥改成 `service.setXxx` 了。

2022-11-28 15:45 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +    return new RSASigner(merchantSerialNumber, privateKey);
上面的 `createCredential` 应该复用这个方法不？

2022-11-30 11:35 UTC, EmmetZC approved these changes

2022-12-01 02:18 UTC, merged