增加自动下载平台证书能力
wechatpay-apiv3/wechatpay-java pull request #69
Opened 2022-11-28 02:14 UTC by lianup

# 使用示例
```java
// 不传入平台证书则自动开启自动下载平台证书能力
    RSAConfig rsaConfig =
        new RSAConfig.Builder()
            .merchantId(MERCHANT_ID)
            .privateKeyFromPath(MERCHANT_PRIVATE_KEY_PATH)
            .merchantSerialNumber(MERCHANT_CERTIFICATE_SERIAL_NUMBER)
            .build();
```
# 设计思路
1. 新增 `SafeSingleScheduleExecutor`，为安全的单例线程池，负责执行平台证书下载任务。
2. 封装证书管理器 `CertificateManager` ，为平台证书管理器，拥有 `SafeSingleScheduleExecutor`， 负责平台证书的定时更新保存。
3. 新增 `RSAAutoCertificateProvider`，实现 `CertificateProvider` 接口。为RSA平台证书提供器，拥有单例的 `RSACertificateManager`，提供根据序列号获取证书、获取有效证书方法。

2022-11-29 12:12 UTC, xy-peng requested changes

2022-11-29 12:12 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/RSAAutoCertificateProvider.java
> +    public Builder credential(Credential credential) {
也提供一个设置私钥的方法吧。回调的场景应该直接拿着私钥来初始化吧。

2022-11-29 12:12 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/http/okhttp/OkHttpClientAdapterBuilder.java
> +  public OkHttpClientAdapterBuilder(
构造函数参数的顺序怎么跟 OkHttpClient 不一样呀

```java
  public OkHttpClientAdapter(Credential credential, Validator validator, okhttp3.OkHttpClient client) ;
```

2022-11-30 03:53 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/RSACertificateManager.java
> +      "https://api.mch.weixin.qq.com/v3/certificates"; // 下载证书url
这里应该修改为传入的类型。

2022-11-30 11:25 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractCertificateManager.java
> +            downloadAndUpdateMerchant(merchantId);
建议把 `CertificateManager` 分层两层。`CertificateManager`只是调度器（不是抽象类），全局只有一个。下载证书的操作收拢到一个新类，比如 `RSACertificateDownloader`（可以有个抽象类）。

2022-12-01 02:46 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractCertificateManager.java
> +    if (certificateMap.get(merchantId) != null) {
没有问题，只是值会被新值覆盖，这里的校验是考虑到有商户信息就没必要再放了，不过如果考虑信息错误需要更新的话，确实需要更新。

2022-12-05 03:42 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +            "One of apiV3Key and wechatPayCertificates must be set.");
这里应该是提示应该调用一次 `xxx()` 或者 `yyy()` 接口来设置，而不是提示变量名。

2022-12-05 03:42 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
可以直接调用 `certificateProvider()`，而且它的优先级高于 `apiv3Key` 和 `wechatPayCertificates`。

感觉容易犯错。

2022-12-05 06:17 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
提供`certificateProvider ()`是为了可以让开发者自定义provider中的HttpClient。
容易犯错是指，开发者可能自己构造provider，但又传入了certificates或者apiv3Key，导致provider被覆盖？

2022-12-05 07:10 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
他自己传入了 `provider` 以后，传 `certificate` 或 `apiv3Key` 就没用了吧

2022-12-05 07:47 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
嗯，这三个互斥，我改下。

2022-12-06 07:21 UTC, xy-peng requested changes

2022-12-06 07:21 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +      throw new IllegalArgumentException("The parameter list of constructor is empty.");
抛出异常的行为，跟 `getCertificate()` 不一致。用 `IllegalArgumentException` 也不对，这不是参数错误。

建议改成用 `Optional` ?

2022-12-06 08:24 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
是不是直接提供三个 Builder 给开发者，一个萝卜一个坑，更简单而不容易出错？

2022-12-06 09:12 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/SafeSingleScheduleExecutor.java
> +    if (getQueue().size() < MAX_QUEUE_CAPACITY) {
重复插入的是指插入多个同商户号对应的平台证书更新的任务？

同一个证书提供器实例，不会出现这种情况。因为每个证书提供器实例对应自己的平台证书下载任务。插入平台证书下载任务是在构造函数，因此只会插入一次。

如果是多个证书提供器实例，对应同样的商户号信息，它们确实会下载相同的平台证书。但是这也是符合预期的，因为每个证书提供器自己管理自己的平台证书下载任务。

2022-12-06 09:16 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +      throw new IllegalArgumentException("The parameter list of constructor is empty.");
其实这里可以不用这个判断，因为certificateMap在实例初始化后就一定不为空。

这里判断去掉，如果没有证书，那就返回null？

2022-12-06 09:21 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/RSAConfig.java
> +      if (this.certificateProvider == null) {
三个Builder，好像不经常见到这种多个Builder的的做法，因为Builder模式就是为了能够让开发者传入可选参数，三个是否有点冗余了？

2022-12-08 07:20 UTC, xy-peng requested changes

2022-12-08 07:20 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +  private final Function<List<X509Certificate>, Verifier> verifierGenerator; // 生成verifier的方法
还是定义一个接口更合适，证书处理器的接口，包括：

+ 从加密 String 到 X.509 证书对象
+ 从 X.509 证书对象列表到 Verifier

证书处理器还是在构造时注入，整体看会更清晰一些。

2022-12-08 08:00 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/SafeSingleScheduleExecutor.java
> +    if (getQueue().size() < MAX_QUEUE_CAPACITY) {
建议一个商户号，一个 Provider 类型只加一次任务

2022-12-12 03:42 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/SafeSingleScheduleExecutor.java
> +    if (getQueue().size() < MAX_QUEUE_CAPACITY) {
每个provider实例是自行管理自己的平台证书下载任务，然后更新平台证书到自身实例。

如果一个商户号，一个Provider类型只加一次任务，假设有a、b、c3个provider，a加了下载任务，b、c没有加，那b、c怎么获取和更新平台证书呢？

2022-12-12 14:59 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/SafeSingleScheduleExecutor.java
> +    if (getQueue().size() < MAX_QUEUE_CAPACITY) {
b/c从a获取证书？

2022-12-12 15:26 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/notification/AbstractRSANotificationConfig.java
> +  private final byte[] apiV3Key;
基类持有`AeadCipher` ?

2022-12-13 02:32 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/notification/AbstractRSANotificationConfig.java
> +  private final byte[] apiV3Key;
如果要持有而非每次都新建一个，那么`verifier`也应当保持一致。

2022-12-15 11:39 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/notification/RSAAutoCertificateNotificationConfig.java
> +      Validator validator = new WechatPay2Validator((serialNumber, message, signature) -> true);
空 Validator 是可以更简单的呀

```java
    private final Validator emptyValidator =
        new Validator() {
          @Override
          public boolean validate(HttpHeaders responseHeaders, String body) {
            return true;
          }
        };
```

2022-12-15 11:40 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/notification/AbstractRSANotificationConfig.java
> +  private final byte[] apiV3Key;
另外，如果是个 `AeadCipher`，这个抽象类国密也可以用了

2022-12-16 03:04 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/AbstractRSAConfigBuilder.java
> +public abstract class AbstractRSAConfigBuilder<T extends AbstractRSAConfigBuilder<T>> {
发现是加载证书用的是RSA的方法

2022-12-16 03:06 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/RSAAutoCertificateConfig.java
> +public class RSAAutoCertificateConfig extends AbstractRSAConfig {
加上 final 关键词吧，避免扩展改变了行为

2022-12-16 03:11 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/RSAAutoCertificateConfig.java
> +      if (httpClient != null && proxy != null) {
减配成只支持 httpClient 的吧，更简单一些，之前 RSAConfig 也不是一直这样嘛。

2022-12-16 03:12 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/RSAAutoCertificateConfig.java
> +      Validator validator = new WechatPay2Validator((serialNumber, message, signature) -> true);
这样会让正常的请求也不验签了？

2022-12-21 05:16 UTC, xy-peng requested changes

2022-12-21 05:16 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +      Map<String, Integer> updatesMap) {
`updateMap`定义成抽象类的成员变量就行了，不需要由子类传给抽象类吗？

另外，也不需要是map，记录provider的商户号下的计数就行了，更简单。

2022-12-21 05:16 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +      Map<String, Validator> validatorMap,
validator 是不是也可以不用map，只关注当前商户号的validator，抽象类自己维护就行了

2022-12-21 08:38 UTC, xy-peng approved these changes
@lianup 辛苦了，不容易……

2022-12-21 09:13 UTC, Eric-Lee-Handyman commented on core/src/main/java/com/wechat/pay/java/core/certificate/AbstractAutoCertificateProvider.java
> +      updateTime += 1;
用 ++ 比较简洁？

2022-12-21 09:18 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/certificate/RSAAutoCertificateProvider.java
> +  }
可以放在 `RSAAutoCertificateProvider` 中？

2022-12-21 09:18 UTC, EmmetZC commented on core/src/main/java/com/wechat/pay/java/core/certificate/CertificateHandler.java
> +  X509Certificate generateCertificate(String certificate);
这个名字有点怪异，从字符串加载证书但是叫 `generateXXX`

@xy-peng

2022-12-21 09:40 UTC, Eric-Lee-Handyman commented on core/src/main/java/com/wechat/pay/java/core/certificate/CertificateHandler.java
> +  X509Certificate generateCertificate(String certificate);
叫 loadCertificate 会合适一些？

2022-12-21 09:47 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/certificate/CertificateHandler.java
> +  X509Certificate generateCertificate(String certificate);
因为Java里的方法就叫做 [generateCertificate](https://docs.oracle.com/javase/8/docs/api/java/security/cert/CertificateFactory.html#generateCertificate-java.io.InputStream-)

2022-12-21 10:49 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/certificate/RSAAutoCertificateProvider.java
> +  }
这个类就是RSAAutoCertificateProvider，没理解这里的意思。

2022-12-22 04:51 UTC, EmmetZC approved these changes

2022-12-22 08:37 UTC, xy-peng approved these changes

2022-12-22 08:43 UTC, merged

2022-12-28 01:17 UTC, taolive commented
RSAAutoCertificateNotificationConfig.这个类在哪里？我是 com.github.wechatpay-apiv3:wechatpay-java:0.2.3版本