增加直连商户下载账单服务
wechatpay-apiv3/wechatpay-java pull request #83
Opened 2022-12-14 11:04 UTC by lianup

2022-12-15 04:09 UTC, TheNorthMemory commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    String hash = ShaUtil.getSha1HexString(fileInputStream);
建议调整`ShaUtil`内部的`BUFFER_SIZE` 为 `16kB`，一般为文件系统的一整块。

2022-12-15 04:09 UTC, TheNorthMemory commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    if (!hash.equals(hashValue)) {
在收付通产品上，账单可能会分文件，这里比较摘要时，可能不准，另外建议用 `timingSafeEquals` 比较，字符串直接比较可能有问题。

2022-12-15 06:13 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    InputStream responseBodyStream = httpClient.download(downloadUrl);
这里我是想把异常抛到外面，让使用者决定处理。

2022-12-15 06:39 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    if (!hash.equals(hashValue)) {
分文件是指？

2022-12-15 06:41 UTC, TheNorthMemory commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    if (!hash.equals(hashValue)) {
> 分文件是指？

账单文件太大，超过1G，文件被切割成多份了，详见 https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_9_5.shtml

2022-12-15 07:07 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    String hash = ShaUtil.getSha1HexString(fileInputStream);
一般会是4或者8kB，调整为4是否比较合适？

2022-12-15 07:16 UTC, lianup commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    if (!hash.equals(hashValue)) {
嗯嗯，这个BillService是用于直接商户下的账单服务，不会有分账单的情况。对于服务商或者其他类型的账单下载，会有单独的BillService。

2022-12-15 07:27 UTC, TheNorthMemory commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    if (!hash.equals(hashValue)) {
> 嗯嗯，这个BillService是用于直接商户下的账单服务，不会有分账单的情况。对于服务商或者其他类型的账单下载，会有单独的BillService。

跟 收付通 那边同学确认下吧，二级商户走直连下载账单时，是否会出现文件太大需要切割情况，如没有则没问题。

2022-12-15 09:04 UTC, TheNorthMemory commented on service/src/main/java/com/wechat/pay/java/service/payments/bill/BillService.java
> +    String hash = ShaUtil.getSha1HexString(fileInputStream);
在`nodejs` stream模块上，一般默认的`highwatermark` 是 [16kb/64kb](https://nodejs.org/api/fs.html#filehandlecreatereadstreamoptions), 之前翻文档的时候特意查过，这个16kb也是文件系统的一个blocksize大小，这可能是脚本语言的一个最佳实践，建议做下测试500M文件试试看，java上哪种缓冲区大小能快些.

2022-12-21 09:09 UTC, xy-peng requested changes

2022-12-21 09:09 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/http/okhttp/OkHttpClientAdapter.java
> +        String.format(
顺便说一句，useragent不用每次都计算，可以算出来保存下来

2022-12-21 09:09 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/util/ShaUtil.java
> +  public static final int BUFFER_SIZE = 4096;
不用的先移除？

2022-12-21 09:09 UTC, xy-peng commented on core/src/test/java/com/wechat/pay/java/core/http/HttpClientTest.java
> +    server.shutdown();
得从 `server.takeRequest()` 取出请求来做一些必要的检查，比如是否携带了 Authorization 等必要的头部

2022-12-23 04:15 UTC, xy-peng approved these changes

2022-12-23 07:09 UTC, lianup commented on core/src/test/java/com/wechat/pay/java/core/http/HttpClientTest.java
> +    server.shutdown();
添加了对authorization、user-agent头的是否为空的校验。

2022-12-23 07:44 UTC, EmmetZC approved these changes

2022-12-23 08:00 UTC, TheNorthMemory commented on core/src/main/java/com/wechat/pay/java/core/http/AbstractHttpClient.java
> +        new HttpRequest.Builder()
这个地方看着可以优化一下，只用一次`build`就可以的哇~
```java
httpRequest = new HttpRequest.Builder()
  .httpMethod(HttpMethod.GET)
  .url(url)
  .addHeader(ACCEPT, "*/*")
  .build();
```

2022-12-23 08:30 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/http/AbstractHttpClient.java
> +        new HttpRequest.Builder()
构建originRequest，主要是为了便于构建authorization。

2022-12-23 08:39 UTC, TheNorthMemory commented on core/src/main/java/com/wechat/pay/java/core/http/AbstractHttpClient.java
> +        new HttpRequest.Builder()
> 构建originRequest，主要是为了便于构建authorization。
是不是原`httpRequest`对象可以先不去执行末尾的 `.build()` ，算完`authorization`再`addHeader().build()`链一下就行了呢

2022-12-23 08:48 UTC, lianup commented on core/src/main/java/com/wechat/pay/java/core/http/AbstractHttpClient.java
> +        new HttpRequest.Builder()
不行的，没构建完之前得不到一个HttpRequest。

2022-12-23 09:18 UTC, xy-peng commented on core/src/main/java/com/wechat/pay/java/core/http/AbstractHttpClient.java
> +        new HttpRequest.Builder()
逻辑没问题，只是看起来不够优雅。

如果有 `HttpRequest.newBuilder(originRequest)` 的方法，代码会看起来舒服一些。

2022-12-23 09:18 UTC, xy-peng approved these changes

2022-12-26 01:57 UTC, merged